CREATE external TABLE IF not exists f_db.flight_tbl (
Srno					  int,
DTE                       date,
OP_UNIQUE_CARRIER         string,        
TAIL_NUM                  string,        
OP_CARRIER_FL_NUM         int,         
ORIGIN_AIRPORT_ID         int,         
ORIGIN                    string,        
ORIGIN_CITY_NAME          string,        
DEST_AIRPORT_ID           int,         
DEST                      string,        
DEST_CITY_NAME            string,        
CRS_DEP_TIME              int,         
DEP_TIME                  float,       
DEP_DELAY_NEW             float,       
DEP_DEL15                 float,       
DEP_TIME_BLK              string,        
CRS_ARR_TIME              int,         
ARR_TIME                  float,       
ARR_DELAY_NEW             float,       
ARR_TIME_BLK              string,        
CANCELLED                 float,       
CANCELLATION_CODE         string,        
CRS_ELAPSED_TIME          float,       
ACTUAL_ELAPSED_TIME       float,       
DISTANCE                  float,       
DISTANCE_GROUP            int,         
CARRIER_DELAY             float,       
WEATHER_DELAY             float,       
NAS_DELAY                 float,       
SECURITY_DELAY            float,       
LATE_AIRCRAFT_DELAY       float,       
AWND                      float,       
PRCP                      float,       
SNOW                      float,       
SNWD                      float,       
TAVG                      float,       
TMAX                      float,       
TOBS                      float,       
WT11                      float,       
LATITUDE                  float,       
LONGITUDE                 float,       
DISPLAY_AIRPORT_NAME      string,        
PASSENGER_HANDLING        int,         
PASS_GEN_SVC_ADMIN        int,         
ARCFT_TRAF_HANDLING_GRP1  int,         
GEN_ARCFT_TRAF_HANDLING   int,         
MANUFACTURE_YEAR          float,       
NUMBER_OF_SEATS           float,       
CARRIER_NAME              string,        
SERVICE_CLASS             string,        
REV_ACRFT_DEP_PERF_510    float,       
REV_PAX_ENP_110           float
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' WITH SERDEPROPERTIES ("separatorChar"= ",", "quoteChar" = "\"") LOCATION '/home/sachin_patel3/localsrcfiles/merged-flight-dataset-2019-20.csv' tblproperties("skip.header.line.count"="1");

Load data local inpath '/home/sachin_patel3/localsrcfiles/merged-flight-dataset-2019-20.csv' overwrite into table f_db.flight_tbl;

     
